# Generated by Django 3.1.7 on 2021-03-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_auto_20210318_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(blank=True, max_length=10, null=True)),
                ('value_coin', models.FloatField(blank=True, null=True)),
                ('value_usd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('depo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.data_user')),
            ],
        ),
    ]
