# Generated by Django 3.1.7 on 2021-03-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20210318_1305'),
        ('transaction', '0002_auto_20210318_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='status_text',
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_roi', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.data_user')),
            ],
        ),
    ]
