# Generated by Django 3.1.7 on 2021-03-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20210318_1931'),
        ('transaction', '0005_bonus_sponsor_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus_sponsor',
            name='for_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.data_user'),
        ),
    ]
