# Generated by Django 3.1.7 on 2021-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_roi_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_pairing',
            name='omset_kanan',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bonus_pairing',
            name='omset_kiri',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
