# Generated by Django 3.1.7 on 2021-03-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20210320_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus_roi',
            name='matching',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
